task03 Валин Глеб
the7winds/scala-2017 pull request #2
Opened 2017-09-24 17:25 UTC by the7winds

2017-09-25 08:57 UTC, adkozlov commented
Добавьте, пожалуйста, @dovchinnikov в качестве ревьюера.

2017-10-08 13:51 UTC, dovchinnikov requested changes

2017-10-08 13:51 UTC, dovchinnikov commented on src/main/scala/ru/spbau/jvm/scala/task03/HangmanBot.scala
> +    implicit msg: Message => {
Зачем здесь implicit?

2017-10-08 13:51 UTC, dovchinnikov commented on src/main/scala/ru/spbau/jvm/scala/task03/Game.scala
> +    Files.lines(dictionaryPath)
Файл читается каждый раз. Так задумано?

2017-10-08 13:51 UTC, dovchinnikov commented on src/main/scala/ru/spbau/jvm/scala/task03/Game.scala
> +  case class GuessSuccess() extends GuessStatus
Почему не object-ы?

2017-10-08 13:51 UTC, dovchinnikov commented on src/main/scala/ru/spbau/jvm/scala/task03/Game.scala
> +    var i = 0
Эта переменная не используется

2017-10-08 13:51 UTC, dovchinnikov commented on src/main/scala/ru/spbau/jvm/scala/task03/Game.scala
> +    val i = 0
Эта переменная не используется

2017-10-08 13:51 UTC, dovchinnikov commented on src/main/scala/ru/spbau/jvm/scala/task03/Game.scala
> +  private val representation = {
Array#fill

2017-10-08 13:51 UTC, dovchinnikov commented on src/main/scala/ru/spbau/jvm/scala/task03/HangmanBot.scala
> +          if (game.finished()) {
Кажется, игра должна удаляться сразу после того, как закончилась.
Сейчас это происходит при получении следующего сообщения

2017-10-08 13:51 UTC, dovchinnikov commented on src/main/scala/ru/spbau/jvm/scala/task03/HangmanBot.scala
> +                val TTT = raw"^\w$$".r.findFirstIn(text)
Очень некрасиво.

2017-10-08 13:51 UTC, dovchinnikov commented on src/main/scala/ru/spbau/jvm/scala/task03/Game.scala
> +class Game(val bot: HangmanBot) {
Ссылка на объект бота нужна, чтобы отправлять сообщения?
Получается у Game нет четкой цели. 

Советую избавиться от этой зависимости. Пусть игра занимается игровой логикой, а бот занимается сообщениями.

2017-10-08 13:51 UTC, dovchinnikov commented on src/main/scala/ru/spbau/jvm/scala/task03/Game.scala
> +  final val MAX_LIVES = 5
Это поле должно быть в объекте.

2017-10-08 13:51 UTC, dovchinnikov commented on src/main/scala/ru/spbau/jvm/scala/task03/Game.scala
> +  var closed = word.length
Это поле, должно быть приватным, как и следующее.

2017-12-02 21:25 UTC, closed without merging